### ISSUE TITLE
ovpn client configuration. Server port hardcoded

### ISSUE THREAD

**Issue by angelbarrera92** [sighupio/furyagent#20]
Ciao team!

While creating a ovpn profile for a client using the command:

```bash
$ furyagent configure openvpn-client --client-name angel --config furyagent.yml
```

`furyagent.yml` example file:

```yaml
storage:
  provider: s3
  bucketName: ${bucketName}
  aws_access_key: ${aws_access_key}
  aws_secret_key: ${aws_secret_key}
  region: ${region}
clusterComponent:
  openvpn:
    certDir: /etc/openvpn/pki
    servers:
      - my.server.ip.address
```

It will create an ovpn file with the port 1194 hardcoded. As it could be customized, we have to find a way to make it variable.

Maybe we can figure out it like:

- `my.server.ip.address`: IP: `my.server.ip.address` port `1194` (default)
- `my.server.ip.address:1194`: IP: `my.server.ip.address` port `1194`
- `my.server.ip.address:1195`: IP: `my.server.ip.address` port `1195`

What do you think?
